name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  make:
    runs-on: macos-latest

    defaults:
      run:
        shell: zsh {0} # ref: https://zenn.dev/shundeveloper/articles/2fdf4bf627072f

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init
        run: make init

      # - name: Brew
      #   run: make brew

      - name: link-vscode
        run: make link-vscode

      - name: macos
        run: make macos
