name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  make:
    runs-on: macos-latest

    defaults:
      run:
        shell: zsh {0} # ref: https://zenn.dev/shundeveloper/articles/2fdf4bf627072f

    steps:
      - name: Clone dotfiles
        run: git clone https://github.com/iloveomelette/dotfiles ~/.dotfiles

      - name: Automatic Installation
        run: cd ~/.dotfiles && make

      - name: VSCode Settings
        run: |
          cd ~/.dotfiles
          mkdir -p ${HOME}/Library/Application\ Support/Code/User
          mkdir -p ${HOME}/Library/Application\ Support/Code/User/snippets
          touch ${HOME}/Library/Application\ Support/Code/User/settings.json
          touch ${HOME}/Library/Application\ Support/Code/User/keybindings.json
          make link-vscode
